homepage:
    path:  /
    defaults: { _controller: TopxiaWebBundle:Default:index }

knowledge_share_list:
    path:  /share/list
    defaults: { _controller: TopxiaWebBundle:Default:shareList }

knowledge_add_comment:
    path:  /comment
    defaults: { _controller: TopxiaWebBundle:Knowledge:addComment }

user_page:
    path:  /user/{id}
    defaults: { _controller: TopxiaWebBundle:User:index }

knowledge_addKnowledge:
    path:  /addKnowledge
    defaults: {_controller: TopxiaWebBundle:Knowledge:addKnowledge }

knowledge_detail:
    path:  /detail/{id}
    defaults: { _controller: TopxiaWebBundle:Knowledge:detail }

theme:
    path: /theme
    defaults: { _controller: TopxiaWebBundle:Theme:index }

theme_follow: 
    path: /theme/{id}/follow
    defaults: { _controller: TopxiaWebBundle:Theme:follow }
    methods: [POST]

theme_unfollow: 
    path: /theme/{id}/unfollow
    defaults: { _controller: TopxiaWebBundle:Theme:unfollow }
    methods: [POST]
