homepage:
    path:  /
    defaults: { _controller: TopxiaWebBundle:Default:index }

my_knowledge_share:
    path:  /knowledge/share
    defaults: { _controller: TopxiaWebBundle:MyKnowledgeShare:index }

my_knowledge_share_edit:
    path: /knowledge/share/{id}/edit
    defaults: { _controller: TopxiaWebBundle:MyKnowledgeShare:edit }

my_knowledge_share_delete:
    path: /knowledge/share/{id}/delete
    defaults: { _controller: TopxiaWebBundle:MyKnowledgeShare:delete }
    methods: [POST]

knowledge_create_comment:
    path:  /comment
    defaults: { _controller: TopxiaWebBundle:Knowledge:createComment }

user_page:
    path:  /user/{id}
    defaults: { _controller: TopxiaWebBundle:User:index }

knowledge_create_knowledge:
    path:  /create/knowledge
    defaults: {_controller: TopxiaWebBundle:Knowledge:createKnowledge }

knowledge_detail:
    path:  /knowledge/{id}
    defaults: { _controller: TopxiaWebBundle:Knowledge:index }

topic:
    path: /topic
    defaults: { _controller: TopxiaWebBundle:Topic:index }

user_follow:
    path: /user/{id}/follow
    defaults: { _controller: TopxiaWebBundle:User:follow }
    methods: [POST]
    
user_unfollow:
    path: /user/{id}/unfollow
    defaults: { _controller: TopxiaWebBundle:User:unfollow }
    methods: [POST]

knowledge_favorite:
    path: /knowledge/favorite/{id}
    defaults: {_controller: TopxiaWebBundle:Knowledge:favorite}

knowledge_unfavorite:
    path: /knowledge/unfavorite/{id}
    defaults: {_controller: TopxiaWebBundle:Knowledge:unfavorite}

knowledge_like:
    path: /knowledge/like/{id}
    defaults: {_controller: TopxiaWebBundle:Knowledge:like}

knowledge_dislike:
    path: /knowledge/dislike/{id}
    defaults: {_controller: TopxiaWebBundle:Knowledge:dislike}

topic_follow: 
    path: /topic/{id}/follow
    defaults: { _controller: TopxiaWebBundle:Topic:follow }
    methods: [POST]

topic_unfollow: 
    path: /topic/{id}/unfollow
    defaults: { _controller: TopxiaWebBundle:Topic:unfollow }
    methods: [POST]

test:
    path: /test
    defaults: { _controller: TopxiaWebBundle:Test:index }

ajax_link:
    path: /link
    defaults: { _controller: TopxiaWebBundle:Ajax:link }
    methods: [POST]

ajax_topic:
    path: /topic
    defaults: { _controller: TopxiaWebBundle:Ajax:topic }
    methods: [POST]

doc_modal: 
    path: /modal/doc
    defaults: { _controller: TopxiaWebBundle:Default:docModal}

link_modal: 
    path: /modal/link
    defaults: { _controller: TopxiaWebBundle:Default:linkModal}

user_favorite:
    path: /user/{userId}/favorite
    defaults: {_controller: TopxiaWebBundle:User:listFavorite}