homepage:
    path:  /
    defaults: { _controller: appBundle:Default:index }

my_knowledge_share:
    path: /my/knowledge/share
    defaults: { _controller: appBundle:MyKnowledgeShare:index }

my_knowledge_share_edit:
    path: /my/knowledge/share/{id}/edit
    defaults: { _controller: appBundle:MyKnowledgeShare:edit }

my_knowledge_share_delete:
    path: /my/knowledge/share/{id}/delete
    defaults: { _controller: appBundle:MyKnowledgeShare:delete }
    methods: [POST]

knowledge_create_comment:
    path:  /comment
    defaults: { _controller: appBundle:Knowledge:createComment }

user_favorites:
    path: /user/{userId}/favorites
    defaults: { _controller: appBundle:User:listFavorites }

user_page:
    path:  /user/{id}
    defaults: { _controller: appBundle:User:index }

knowledge_create_knowledge:
    path:  /create/knowledge
    defaults: {_controller: appBundle:Knowledge:createKnowledge }

knowledge_detail:
    path:  /knowledge/{id}
    defaults: { _controller: appBundle:Knowledge:index }

topic:
    path: /topic
    defaults: { _controller: appBundle:Topic:index }

user_follow:
    path: /user/{id}/follow
    defaults: { _controller: appBundle:User:follow }
    methods: [POST]

user_unfollow:
    path: /user/{id}/unfollow
    defaults: { _controller: appBundle:User:unfollow }
    methods: [POST]

user_create_toread:
    path: /user/{id}/create/toread
    defaults: { _controller: appBundle:User:createToread }
    methods: [POST]

user_delete_toread:
    path: /user/{id}/delete/toread
    defaults: { _controller: appBundle:User:deleteToread }
    methods: [POST]

knowledge_favorite:
    path: /knowledge/favorite/{id}
    defaults: {_controller: appBundle:Knowledge:favorite}

knowledge_unfavorite:
    path: /knowledge/unfavorite/{id}
    defaults: {_controller: appBundle:Knowledge:unfavorite}

knowledge_like:
    path: /knowledge/like/{id}
    defaults: {_controller: appBundle:Knowledge:like}

knowledge_dislike:
    path: /knowledge/dislike/{id}
    defaults: {_controller: appBundle:Knowledge:dislike}

topic_follow: 
    path: /topic/{id}/follow
    defaults: { _controller: appBundle:Topic:follow }
    methods: [POST]

topic_unfollow: 
    path: /topic/{id}/unfollow
    defaults: { _controller: appBundle:Topic:unfollow }
    methods: [POST]

test:
    path: /test
    defaults: { _controller: appBundle:Test:index }

ajax_link:
    path: /link
    defaults: { _controller: appBundle:Ajax:link }
    methods: [POST]

ajax_topic:
    path: /topic
    defaults: { _controller: appBundle:Ajax:topic }
    methods: [POST]

doc_modal: 
    path: /modal/doc
    defaults: { _controller: appBundle:Default:docModal}

link_modal: 
    path: /modal/link
    defaults: { _controller: appBundle:Default:linkModal}

my_favorites:
    path: /my/favorites
    defaults: {_controller: appBundle:User:myFavorites}

my_followeds:
    path: /my/followeds/{type}
    defaults: {_controller: appBundle:User:myFolloweds}

user_favorite:
    path: /user/{userId}/favorite
    defaults: {_controller: appBundle:User:listFavorite}

top_knowledge:
    path: /top/knowledge
    defaults: { _controller: appBundle:Default:listTopKnowledges }

top_topic:
    path: /top/topic
    defaults: { _controller: appBundle:Default:listTopTopics }

top_user:
    path: /top/user
    defaults: { _controller: appBundle:Default:listTopUsers }

knowledge_finish_learn:
    path: /knowledge/{id}/learn
    defaults: {_controller: appBundle:Knowledge:finishLearn}

login:
  path:      /login
  defaults:  { _controller: appBundle:Auth:login }

login_check:
  path:      /login_check

logout:
  path:      /logout
  defaults:  { _controller: appBundle:Auth:logout }

register:
  path:      /register
  defaults:  { _controller: appBundle:Auth:register }

my_knowledge_share_todolist: 
    path: /my/knowledge/todolist
    defaults: { _controller: TopxiaWebBundle:MyKnowledgeShare:toDoList}