homepage:
    path:     /
    defaults: { _controller: TopxiaWebBundle:Default:index }
    
knowledge_share_list:
    path:  /share/list
    defaults: { _controller: TopxiaWebBundle:Default:shareList }

knowledge_addKnowledge: 
    path: /addlink
    defaults: {_controller: TopxiaWebBundle:Knowledge:addKnowledge }

knowledge_detail:
    path:     /detail/{id}
    defaults: { _controller: TopxiaWebBundle:Knowledge:detail }
    methods: [GET]

theme:
    path: /theme
    defaults: { _controller: TopxiaWebBundle:Theme:index }
