homepage:
    path:  /
    defaults: { _controller: TopxiaWebBundle:Default:index }

knowledge_share_list:
    path:  /share/list
    defaults: { _controller: TopxiaWebBundle:Default:shareList }

knowledge_add_comment:
    path:  /comment
    defaults: { _controller: TopxiaWebBundle:Knowledge:addComment }

user_page:
    path:  /user/{id}
    defaults: { _controller: TopxiaWebBundle:User:index }

knowledge_addKnowledge:
    path:  /addKnowledge
    defaults: {_controller: TopxiaWebBundle:Knowledge:add }

knowledge_detail:
    path:  /knowledge/{id}
    defaults: { _controller: TopxiaWebBundle:Knowledge:index }

topic:
    path: /topic
    defaults: { _controller: TopxiaWebBundle:Topic:index }

user_follow:
    path: /user/{id}/follow
    defaults: { _controller: TopxiaWebBundle:User:follow }
    methods: [POST]
    
user_unfollow:
    path: /user/{id}/unfollow
    defaults: { _controller: TopxiaWebBundle:User:unfollow }
    methods: [POST]

MyKnowledge_addCollection:
    path: /addCollection/{knowledgeId}
    defaults: {_controller: TopxiaWebBundle:MyKnowledge:addCollection}

MyKnowledge_delCollection:
    path: /delCollection/{knowledgeId}
    defaults: {_controller: TopxiaWebBundle:MyKnowledge:delCollection}

topic_follow: 
    path: /topic/{id}/follow
    defaults: { _controller: TopxiaWebBundle:Topic:follow }
    methods: [POST]

topic_unfollow: 
    path: /topic/{id}/unfollow
    defaults: { _controller: TopxiaWebBundle:Topic:unfollow }
    methods: [POST]
