system_web_homepage:
    path:     /
    defaults: { _controller: TopxiaWebBundle:Default:index }

knowledge_detail:
    path:     /detail/{id}
    defaults: { _controller: TopxiaWebBundle:Knowledge:detail }
    methods: [GET]

