system_web:
    resource: "@SystemWebBundle/Resources/config/routing.yml"
    prefix:   /

#system_user:
#    resource: "@SystemUserBundle/Resources/config/routing.yml"
#    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
