# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    app.current_user.class: Topxia\WebBundle\Security\CurrentUser

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    biz:
      class: Topxia\BizKernel
      arguments: ["%biz%", "@service_container"]

    app.asset_helper.twig_extension:
        class: Topxia\WebBundle\Twig\AssetHelperExtension
        public: false
        tags:
            - { name: twig.extension }

    app.user_provider:
        class: Topxia\WebBundle\Security\UserProvider
        arguments: ["@biz"]
